### PR TITLE
Improved readability of the FAQ section

### PR DESCRIPTION
**Pull request by scottshuffler**
Took me a bit to understand what was happening in the FAQ. Laid it out in a way I thought was more readable.

### CODE REVIEW

**Comment by pmoody-** [comment]
Hey Scott, thanks for the pr.

can you 'sign' the cla? https://cla-assistant.io/uber/pam-ussh?pullRequest=3

**Comment by scottshuffler** [comment]
@pmoody- Done!

**Comment by pmoody-** [comment]
Hey Scott, can you double check that the CLA has been signed? the cla bot is telling that it's still unsigned.

**Comment by scottshuffler** [comment]
@pmoody- Strange! Definetly shows that I did it on my end. Can we get it reset so I can do it again?

 http://imgur.com/a/pY2hZ

**Comment by pmoody-** [comment]
merged. thanks!

**Pull request merged**
